### ISSUE TITLE
Use w3 template for themes

### ISSUE THREAD

**Issue by B4rb3rouss** [BlogoText/blogotext#312]
Small idea : use [w3](https://www.w3schools.com/w3css/) template for theme.
This would make theming much easier. 
This template seems well thought.
Some elements of the appearance should be in theme, not in .php files (i.e. form to post comments which use sprites)

**Comment by ragnar76** [comment]
they look really good but to be honest, wait for v4 after changes to the theming enginge are done and then jump in. it's not that hard. i've made a theme using bootstrap in less than 2 hours from scratch. porting them should be very quick

**Comment by remrem** [comment]
for admin or public template ?

**Comment by B4rb3rouss** [comment]
> for admin or public template ?

It could be both, but for public before all. All the necessary seems here : 
- support for mobile
- lightbox and image galleries 
- small animations
- ...

This is just a suggestion to think about the theme structure in 4.*.

-- 
thuban

**Comment by remrem** [comment]
As @ragnar76 says, we can think about that for 4.0.

But right now, for the Admin UI, I don't really want to change the template (to a framework or a complete reboot).     I think the current UI (based on "material design") is still relevant and simple. (bonus, I have a small thing coming very soon).

For the public side, yep, a new default template for the 4.0 can be a good thing, using a template or not. But, if we go to a new template, first thing first, we need a idea of what we want and then, choose a technical/graphic solution.

_Not sure of my english for this shot ..._

**Comment by B4rb3rouss** [comment]
I agree, the admin part shouldn't be a priority.
But for the public part... Being able to theme its own blog is very important to user, this give an identity to it. But when I seen class like ``class="form-commentaire`` hard-coded, this make theming hard, or at least annoying. Something like "http://plucss.pluxml.org/" would be ideal.
Just a thougt, but it seems quite important to me to think about this.

**Comment by remrem** [comment]
Ok, my bad, now I understand, you don't want to use a framework to create a new public default template, you want to provide a CSS framework for all users who want to create a BT template (like plucss.pluxml.org) so I can give you reply, "nop", BT will no provide any css/html/js framework for the public side. We are not enough people to suply seriously a css framework, we can talk about that after v4.0, but for now, there is a lot of work to do before thinking seriously about that.           
But, I think you gonna love the idea, since we seem's to be agreed on this point : BT don't have to generate html (like your example `class="form-commentaire"` ).

With the future template engine, the target is to provide (BT side) all the things to allow web designer to create a `comments-form.html` (to stay with the example) with the HTML structure of the user want to use, like 
```
<form id="as-you-wish" class="a-custom-class-or-not">
   <wathever>
   <label for="as-you-wish">{lang_comments_form_name_label}</label>
   <input type="text" name="{comments_form_name}" value="{comment_form_value}" />
   ....
   {form_token}
   {form_captcha}
   <input type="submit" value="{lang_comments_form_submit}>
</form>
   
```
In this example, the HTML structure is not handled by BT, BT play with some {key_word} to provide datas, like language support (optional), values (stored pseudo, website...), security ... and you can wrap this as you want, with your CSS/HTML/JS/framework or custom...                    
So, for the web designer, no framework imposed, no headache with a new framework to learn, just use few technical tags (datas, language).           For us, no browser compatibility issues, no request for modification to the framework (...) just provide a robust system (`str_replace` is a good friend), and some documentation...

So with this engine, if you want to use the W3C framework, ragnar76 (for the example ;) ) want to use boostrap and me "material design", we just need some HTML/CSS basics, to know/read our framework documentation and read the BT documentation about templating...

Additional points, if you want a template for you, with only one language support, you can skip {lang_*} tags, so you need to know/read about so the technical tags (so not so much).

What do you think of this solution ?

**Comment by B4rb3rouss** [comment]
I don't think a full framework is necessary for now too. Your idea is great, and should come with some elements to make theming easier : 
- no "class=***" hard coded, this is so frustrating
- Well documented example (very important)
- ???

**Comment by ragnar76** [comment]
i'm not bound to bootstrap but this is what i know best :)

**Comment by remrem** [comment]
Je clôture cette issue.
P.S. pour ne pas perdre la discussion #211
